[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11"
]
build-backend = "setuptools.build_meta"

[project]
name = "undi"
description = "Muon-Nuclear Dipolar Interaction"
version = "1.1"
authors = [
    { name = "Pietro Bonfa", email = "bonfus@gmail.com" }
]
readme = "README.rst"
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Programming Language :: Python :: 3 :: Only",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Physics"
]
keywords = ["muSR spin nuclear"]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.0",
    "qutip",
    "pybind11"
]

[tool.setuptools.packages.find]
include = ["undi*"]

[tool.setuptools.package-data]
"undi.kubo_toyabe" = ["*.txt"]

[project.optional-dependencies]
fast_cpp = ["pybind11"]
progress_bar = ["tqdm"]

[project.urls]
Source = "http://github.com/bonfus/undi"
